name: CI

env:
  # Treat all Rust warnings as errors in CI (builds, tests, clippy, examples)
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain (rustfmt)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
      - name: rustfmt check
        run: cargo fmt --all -- --check

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain (clippy)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
      - name: Clippy (library strict)
        run: cargo clippy --lib --all-features -- -D warnings
      - name: Clippy (bins/examples/tests info)
        run: cargo clippy --bins --examples --tests --all-features

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
      - name: cargo test
        run: cargo test --all-features --workspace --quiet
